version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    env_file:
      - .env
    volumes:
      - .:/app

  cache:
    image: redis:latest
    container_name: redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    ports:
      - "6379:6379"

  db:
    image: postgres:12
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - .\postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: